# Generated by Django 5.1.1 on 2024-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TASKapp", "0003_rename_task_id_sharedtask_task_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="task_id",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
    ]
