# Generated by Django 5.1.1 on 2024-10-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TASKapp", "0005_rename_task_id_activitylog_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedtask",
            name="task_name",
        ),
    ]
